"""Initial migration with all models

Revision ID: 2d8d9cbf6749
Revises: 
Create Date: 2025-11-13 21:31:53.946413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8d9cbf6749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('blog_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title_fr', sa.String(length=300), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('excerpt_fr', sa.Text(), nullable=True),
    sa.Column('excerpt_en', sa.Text(), nullable=True),
    sa.Column('content_fr', sa.Text(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('featured_image_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('category_fr', sa.String(length=100), nullable=True),
    sa.Column('category_en', sa.String(length=100), nullable=True),
    sa.Column('tags_fr', sa.Text(), nullable=True),
    sa.Column('tags_en', sa.Text(), nullable=True),
    sa.Column('meta_title_fr', sa.String(length=200), nullable=True),
    sa.Column('meta_title_en', sa.String(length=200), nullable=True),
    sa.Column('meta_description_fr', sa.Text(), nullable=True),
    sa.Column('meta_description_en', sa.Text(), nullable=True),
    sa.Column('meta_keywords_fr', sa.Text(), nullable=True),
    sa.Column('meta_keywords_en', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['featured_image_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.create_index('idx_blog_published', ['is_published', 'published_at'], unique=False)
        batch_op.create_index('idx_blog_slug', ['slug'], unique=False)

    op.create_table('collection_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_fr', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('button_text_fr', sa.String(length=100), nullable=True),
    sa.Column('button_text_en', sa.String(length=100), nullable=True),
    sa.Column('button_link', sa.String(length=500), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_fr', sa.Text(), nullable=True),
    sa.Column('value_en', sa.Text(), nullable=True),
    sa.Column('field_type', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('button_link', sa.String(length=500), nullable=True),
    sa.Column('button_link_fr', sa.String(length=500), nullable=True),
    sa.Column('button_link_en', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['content_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'key', name='unique_section_key')
    )
    op.create_table('section_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_fr', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('subtitle_fr', sa.String(length=300), nullable=True),
    sa.Column('subtitle_en', sa.String(length=300), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('button_text_fr', sa.String(length=100), nullable=True),
    sa.Column('button_text_en', sa.String(length=100), nullable=True),
    sa.Column('button_link', sa.String(length=500), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('background_color', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seo_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_slug', sa.String(length=100), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('og_title', sa.String(length=200), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('og_image_id', sa.Integer(), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('structured_data_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['og_image_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_slug')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('client_title_fr', sa.String(length=200), nullable=True),
    sa.Column('client_title_en', sa.String(length=200), nullable=True),
    sa.Column('client_company', sa.String(length=200), nullable=True),
    sa.Column('client_photo_id', sa.Integer(), nullable=True),
    sa.Column('content_fr', sa.Text(), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('meta_title_fr', sa.String(length=200), nullable=True),
    sa.Column('meta_title_en', sa.String(length=200), nullable=True),
    sa.Column('meta_description_fr', sa.Text(), nullable=True),
    sa.Column('meta_description_en', sa.Text(), nullable=True),
    sa.Column('meta_keywords_fr', sa.Text(), nullable=True),
    sa.Column('meta_keywords_en', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_photo_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.create_index('idx_testimonial_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_testimonial_published', ['is_published', 'display_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_index('idx_testimonial_published')
        batch_op.drop_index('idx_testimonial_featured')

    op.drop_table('testimonials')
    op.drop_table('seo_meta')
    op.drop_table('section_panels')
    op.drop_table('content_fields')
    op.drop_table('collection_slides')
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.drop_index('idx_blog_slug')
        batch_op.drop_index('idx_blog_published')

    op.drop_table('blog_articles')
    op.drop_table('site_settings')
    op.drop_table('image_assets')
    op.drop_table('content_sections')
    op.drop_table('contacts')
    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
