"""Initial migration with all models including CollectionSlide and SectionPanel

Revision ID: a79a58b8ebad
Revises: 
Create Date: 2025-11-13 21:10:01.348933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79a58b8ebad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_fr', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('button_text_fr', sa.String(length=100), nullable=True),
    sa.Column('button_text_en', sa.String(length=100), nullable=True),
    sa.Column('button_link', sa.String(length=500), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_fr', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('subtitle_fr', sa.String(length=300), nullable=True),
    sa.Column('subtitle_en', sa.String(length=300), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('button_text_fr', sa.String(length=100), nullable=True),
    sa.Column('button_text_en', sa.String(length=100), nullable=True),
    sa.Column('button_link', sa.String(length=500), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('background_color', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_panels')
    op.drop_table('collection_slides')
    # ### end Alembic commands ###
